using System;
using System.Linq;

namespace Assets
{
    internal struct RepublicanDayName
    {
        public int Day;
        public RepublicanMonth Month;
        public string Name;
        public string Namesake;

        public override string ToString()
        {
            return $"{Month} {Day} ({Name}/{Namesake})";
        }

        public Season GetSeason()
        {
            switch (Month)
            {
                case RepublicanMonth.Vendemaire:
                case RepublicanMonth.Brumaire:
                case RepublicanMonth.Frimaire:
                    return Season.Autumn;
                case RepublicanMonth.Nivose:
                case RepublicanMonth.Pluviose:
                case RepublicanMonth.Ventose:
                    return Season.Winter;
                case RepublicanMonth.Germinal:
                case RepublicanMonth.Floreal:
                case RepublicanMonth.Prairial:
                    return Season.Spring;
                case RepublicanMonth.Messidor:
                case RepublicanMonth.Thermidor:
                case RepublicanMonth.Fructidor:
                    return Season.Summer;
                default:
                    throw new ArgumentException(Month.ToString());
            }
        }
    }

    internal static class Data
    {
        private readonly static RepublicanDayName[] RepublicanDays = new RepublicanDayName[]{
            new RepublicanDayName { Day = 1, Name= "RAISIN", Namesake = "GRAPE", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 2, Name= "SAFRAN", Namesake = "SAFFRON", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 3, Name= "CHATAIGNE", Namesake = "CHESTNUT", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 4, Name= "COLCHIQUE", Namesake = "AUTUMN CROCUS", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 5, Name= "CHEVAL", Namesake = "HORSE", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 6, Name= "BALSAMINE", Namesake = "IMPATIENS", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 7, Name= "CAROTTE", Namesake = "CARROT", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 8, Name= "AMARANTHE", Namesake = "AMARANTH", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 9, Name= "PANAIS", Namesake = "PARSNIP", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 10, Name= "CUVE", Namesake = "VAT", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 11, Name= "POMME DE TERRE", Namesake = "POTATO", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 12, Name= "IMMORTELLE", Namesake = "STRAWFLOWER", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 13, Name= "POTIRON", Namesake = "WINTER SQUASH", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 14, Name= "RESEDA", Namesake = "MIGNONETTE", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 15, Name= "ANE", Namesake = "DONKEY", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 16, Name= "BELLE DE NUIT", Namesake = "FOUR O'CLOCK FLOWER", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 17, Name= "CITROUILLE", Namesake = "PUMPKIN", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 18, Name= "SARRASIN", Namesake = "BUCKWHEAT", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 19, Name= "TOURNESOL", Namesake = "SUNFLOWER", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 20, Name= "PRESSOIR", Namesake = "WINE-PRESS", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 21, Name= "CHANVRE", Namesake = "HEMP", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 22, Name= "PECHE", Namesake = "PEACH", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 23, Name= "NAVET", Namesake = "TURNIP", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 24, Name= "AMARYLLIS", Namesake = "AMARYLLIS", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 25, Name= "BOEUF", Namesake = "OX", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 26, Name= "AUBERGINE", Namesake = "EGGPLANT", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 27, Name= "PIMENT", Namesake = "CHILI PEPPER", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 28, Name= "TOMATE", Namesake = "TOMATO", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 29, Name= "ORGE", Namesake = "BARLEY", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 30, Name= "TONNEAU", Namesake = "BARREL", Month = RepublicanMonth.Vendemaire },
            new RepublicanDayName { Day = 1, Name= "POMME", Namesake = "APPLE", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 2, Name= "CELERI", Namesake = "CELERY", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 3, Name= "POIRE", Namesake = "PEAR", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 4, Name= "BETTERAVE", Namesake = "BEETROOT", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 5, Name= "OIE", Namesake = "GOOSE", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 6, Name= "HELIOTROPE", Namesake = "HELIOTROPE", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 7, Name= "FIGUE", Namesake = "COMMON FIG", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 8, Name= "SCORSONERE", Namesake = "BLACK SALSIFY", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 9, Name= "ALISIER", Namesake = "CHEQUER TREE", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 10, Name= "CHARRUE", Namesake = "PLOUGH", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 11, Name= "SALSIFIS", Namesake = "SALSIFY", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 12, Name= "MACRE", Namesake = "WATER CALTROP", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 13, Name= "TOPINAMBOUR", Namesake = "JERUSALEM ARTICHOKE", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 14, Name= "ENDIVE", Namesake = "ENDIVE", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 15, Name= "DINDON", Namesake = "TURKEY", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 16, Name= "CHERVIS", Namesake = "SKIRRET", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 17, Name= "CRESSON", Namesake = "WATERCRESS", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 18, Name= "DENTELAIRE", Namesake = "LEADWORTS", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 19, Name= "GRENADE", Namesake = "POMEGRANATE", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 20, Name= "HERSE", Namesake = "HARROW", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 21, Name= "BACCHANTE", Namesake = "BACCHARIS", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 22, Name= "AZEROLE", Namesake = "AZAROLE", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 23, Name= "GARANCE", Namesake = "MADDER", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 24, Name= "ORANGE", Namesake = "ORANGE", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 25, Name= "FAISAN", Namesake = "PHEASANT", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 26, Name= "PISTACHE", Namesake = "PISTACHIO NUT", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 27, Name= "MACJONC", Namesake = "TUBEROUS PEA", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 28, Name= "COING", Namesake = "QUINCE", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 29, Name= "CORMIER", Namesake = "SERVICE TREE", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 30, Name= "ROULEAU", Namesake = "ROLLER", Month = RepublicanMonth.Brumaire },
            new RepublicanDayName { Day = 1, Name= "RAIPONCE", Namesake = "RAMPION", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 2, Name= "TURNEPS", Namesake = "CATTLE TURNIP", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 3, Name= "CHICOREE", Namesake = "CHICORY", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 4, Name= "NEFLE", Namesake = "MEDLAR", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 5, Name= "COCHON", Namesake = "PIG", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 6, Name= "MACHE", Namesake = "LAMB'S LETTUCE", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 7, Name= "CHOU-FLEUR", Namesake = "CAULIFLOWER", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 8, Name= "MIEL", Namesake = "HONEY", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 9, Name= "GENIEVRE", Namesake = "JUNIPER", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 10, Name= "PIOCHE", Namesake = "PICKAXE", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 11, Name= "CIRE", Namesake = "WAX", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 12, Name= "RAIFORT", Namesake = "HORSERADISH", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 13, Name= "CEDRE", Namesake = "CEDAR TREE", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 14, Name= "SAPIN", Namesake = "FIR", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 15, Name= "CHEVREUIL", Namesake = "ROE DEER", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 16, Name= "AJONC", Namesake = "GORSE", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 17, Name= "CYPRES", Namesake = "CYPRESS TREE", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 18, Name= "LIERRE", Namesake = "IVY", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 19, Name= "SABINE", Namesake = "SAVIN JUNIPER", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 20, Name= "HOYAU", Namesake = "FORK HOE", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 21, Name= "ERABLE à SUCRE", Namesake = "SUGAR MAPLE", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 22, Name= "BRUYERE", Namesake = "HEATHER", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 23, Name= "ROSEAU", Namesake = "REED PLANT", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 24, Name= "OSEILLE", Namesake = "SORREL", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 25, Name= "GRILLON", Namesake = "CRICKET", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 26, Name= "PIGNON", Namesake = "PINE NUT", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 27, Name= "LIEGE", Namesake = "CORK", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 28, Name= "TRUFFE", Namesake = "TRUFFLE", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 29, Name= "OLIVE", Namesake = "OLIVE", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 30, Name= "PELLE", Namesake = "SHOVEL", Month = RepublicanMonth.Frimaire },
            new RepublicanDayName { Day = 1, Name= "TOURBE", Namesake = "PEAT", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 2, Name= "HOUILLE", Namesake = "COAL", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 3, Name= "BITUME", Namesake = "BITUMEN", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 4, Name= "SOUFRE", Namesake = "SULPHUR", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 5, Name= "CHIEN", Namesake = "DOG", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 6, Name= "LAVE", Namesake = "LAVA", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 7, Name= "TERRE VEGETALE", Namesake = "TOPSOIL", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 8, Name= "FUMIER", Namesake = "MANURE", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 9, Name= "SALPETRE", Namesake = "SALTPETER", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 10, Name= "FLEAU", Namesake = "FLAIL", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 11, Name= "GRANIT", Namesake = "GRANITE", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 12, Name= "ARGILE", Namesake = "CLAY", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 13, Name= "ARDOISE", Namesake = "SLATE", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 14, Name= "GRES", Namesake = "SANDSTONE", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 15, Name= "LAPIN", Namesake = "RABBIT", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 16, Name= "SILEX", Namesake = "FLINT", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 17, Name= "MARNE", Namesake = "MARL", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 18, Name= "PIERRE à CHAUX", Namesake = "LIMESTONE", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 19, Name= "MARBRE", Namesake = "MARBLE", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 20, Name= "VAN", Namesake = "WINNOWING FAN", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 21, Name= "PIERRE à PLATRE", Namesake = "GYPSUM", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 22, Name= "SEL", Namesake = "SALT", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 23, Name= "FER", Namesake = "IRON", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 24, Name= "CUIVRE", Namesake = "COPPER", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 25, Name= "CHAT", Namesake = "CAT", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 26, Name= "ETAIN", Namesake = "TIN", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 27, Name= "PLOMB", Namesake = "LEAD", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 28, Name= "ZINC", Namesake = "ZINC", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 29, Name= "MERCURE", Namesake = "MERCURY", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 30, Name= "CRIBLE", Namesake = "SIEVE", Month = RepublicanMonth.Nivose },
            new RepublicanDayName { Day = 1, Name= "LAUREOLE", Namesake = "SPURGE-LAUREL", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 2, Name= "MOUSSE", Namesake = "MOSS", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 3, Name= "FRAGON", Namesake = "BUTCHER'S BROOM", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 4, Name= "PERCE-NEIGE", Namesake = "SNOWDROP", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 5, Name= "TAUREAU", Namesake = "BULL", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 6, Name= "LAURIER-THYM", Namesake = "LAURUSTINUS", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 7, Name= "AMADOUVIER", Namesake = "TINDER POLYPORE", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 8, Name= "MEZEREON", Namesake = "DAPHNE MEZEREUM", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 9, Name= "PEUPLIER", Namesake = "POPLAR", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 10, Name= "COIGNEE", Namesake = "AXE", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 11, Name= "ELLEBORE", Namesake = "HELLEBORE", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 12, Name= "BROCOLI", Namesake = "BROCCOLI", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 13, Name= "LAURIER", Namesake = "BAY LAUREL", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 14, Name= "AVELINIER", Namesake = "FILBERT", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 15, Name= "VACHE", Namesake = "COW", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 16, Name= "BUIS", Namesake = "BOX TREE", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 17, Name= "LICHEN", Namesake = "LICHEN", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 18, Name= "IF", Namesake = "YEW TREE", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 19, Name= "PULMONAIRE", Namesake = "LUNGWORT", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 20, Name= "SERPETTE", Namesake = "BILLHOOK", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 21, Name= "THLASPI", Namesake = "PENNYCRESS", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 22, Name= "THIMELE", Namesake = "ROSE DAPHNE", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 23, Name= "CHIENDENT", Namesake = "COUCH GRASS", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 24, Name= "TRAINASSE", Namesake = "COMMON KNOTGRASS", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 25, Name= "LIEVRE", Namesake = "HARE", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 26, Name= "GUEDE", Namesake = "WOAD", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 27, Name= "NOISETIER", Namesake = "HAZEL", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 28, Name= "CYCLAMEN", Namesake = "CYCLAMEN", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 29, Name= "CHELIDOINE", Namesake = "CELANDINE", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 30, Name= "TRAINEAU", Namesake = "SLEIGH", Month = RepublicanMonth.Pluviose },
            new RepublicanDayName { Day = 1, Name= "TUSSILAGE", Namesake = "COLTSFOOT", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 2, Name= "CORNOUILLER", Namesake = "DOGWOOD", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 3, Name= "VIOLIER", Namesake = "MATTHIOLA", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 4, Name= "TROENE", Namesake = "PRIVET", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 5, Name= "BOUC", Namesake = "BILLYGOAT", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 6, Name= "ASARET", Namesake = "WILD GINGER", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 7, Name= "ALATERNE", Namesake = "ITALIAN BUCKTHORN", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 8, Name= "VIOLETTE", Namesake = "VIOLET", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 9, Name= "MARCEAU", Namesake = "GOAT WILLOW", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 10, Name= "BECHE", Namesake = "SPADE", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 11, Name= "NARCISSE", Namesake = "NARCISSUS", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 12, Name= "ORME", Namesake = "ELM", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 13, Name= "FUMETERRE", Namesake = "COMMON FUMITORY", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 14, Name= "VELAR", Namesake = "HEDGE MUSTARD", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 15, Name= "CHEVRE", Namesake = "GOAT", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 16, Name= "EPINARD", Namesake = "SPINACH", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 17, Name= "DORONIC", Namesake = "DORONICUM", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 18, Name= "MOURON", Namesake = "PIMPERNEL", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 19, Name= "CERFEUIL", Namesake = "CHERVIL", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 20, Name= "CORDEAU", Namesake = "TWINE", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 21, Name= "MANDRAGORE", Namesake = "MANDRAKE", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 22, Name= "PERSIL", Namesake = "PARSLEY", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 23, Name= "COCHLEARIA", Namesake = "SCURVY-GRASS", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 24, Name= "PAQUERETTE", Namesake = "DAISY", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 25, Name= "THON", Namesake = "TUNA", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 26, Name= "PISSENLIT", Namesake = "DANDELION", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 27, Name= "SYLVIE", Namesake = "WOOD ANEMONE", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 28, Name= "CAPILLAIRE", Namesake = "MAIDENHAIR FERN", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 29, Name= "FRENE", Namesake = "ASH TREE", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 30, Name= "PLANTOIR", Namesake = "DIBBER", Month = RepublicanMonth.Ventose },
            new RepublicanDayName { Day = 1, Name= "PRIMEVERE", Namesake = "PRIMROSE", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 2, Name= "PLATANE", Namesake = "PLANE TREE", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 3, Name= "ASPERGE", Namesake = "ASPARAGUS", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 4, Name= "TULIPE", Namesake = "TULIP", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 5, Name= "POULE", Namesake = "HEN", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 6, Name= "BETTE", Namesake = "CHARD", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 7, Name= "BOULEAU", Namesake = "BIRCH", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 8, Name= "JONQUILLE", Namesake = "DAFFODIL", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 9, Name= "AULNE", Namesake = "ALDER", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 10, Name= "COUVOIR", Namesake = "INCUBATOR", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 11, Name= "PERVENCHE", Namesake = "PERIWINKLE", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 12, Name= "CHARME", Namesake = "HORNBEAM", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 13, Name= "MORILLE", Namesake = "MOREL", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 14, Name= "HETRE", Namesake = "BEECH TREE", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 15, Name= "ABEILLE", Namesake = "BEE", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 16, Name= "LAITUE", Namesake = "LETTUCE", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 17, Name= "MELEZE", Namesake = "LARCH", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 18, Name= "CIGUE", Namesake = "HEMLOCK", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 19, Name= "RADIS", Namesake = "RADISH", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 20, Name= "RUCHE", Namesake = "BEEHIVE", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 21, Name= "GAINIER", Namesake = "JUDAS TREE", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 22, Name= "ROMAINE", Namesake = "ROMAINE LETTUCE", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 23, Name= "MARRONNIER", Namesake = "HORSE CHESTNUT", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 24, Name= "ROQUETTE", Namesake = "ARUGULA", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 25, Name= "PIGEON", Namesake = "PIGEON", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 26, Name= "LILAS", Namesake = "LILAC", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 27, Name= "ANEMONE", Namesake = "ANEMONE", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 28, Name= "PENSEE", Namesake = "PANSY", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 29, Name= "MYRTILLE", Namesake = "BILBERRY", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 30, Name= "GREFFOIR", Namesake = "GRAFTING KNIFE", Month = RepublicanMonth.Germinal },
            new RepublicanDayName { Day = 1, Name= "ROSE", Namesake = "ROSE", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 2, Name= "CHENE", Namesake = "OAK TREE", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 3, Name= "FOUGERE", Namesake = "FERN", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 4, Name= "AUBEPINE", Namesake = "HAWTHORN", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 5, Name= "ROSSIGNOL", Namesake = "NIGHTINGALE", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 6, Name= "ANCOLIE", Namesake = "COMMON COLUMBINE", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 7, Name= "MUGUET", Namesake = "LILY OF THE VALLEY", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 8, Name= "CHAMPIGNON", Namesake = "BUTTON MUSHROOM", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 9, Name= "HYACINTHE", Namesake = "HYACINTH", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 10, Name= "RATEAU", Namesake = "RAKE", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 11, Name= "RHUBARBE", Namesake = "RHUBARB", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 12, Name= "SAINFOIN", Namesake = "SAINFOIN", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 13, Name= "BATON D'OR", Namesake = "WALLFLOWER", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 14, Name= "CHAMERISIER", Namesake = "FAN PALM TREE", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 15, Name= "VER à SOIE", Namesake = "SILKWORM", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 16, Name= "CONSOUDE", Namesake = "COMFREY", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 17, Name= "PIMPRENELLE", Namesake = "SALAD BURNET", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 18, Name= "CORBEILLE D'OR", Namesake = "BASKET OF GOLD", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 19, Name= "ARROCHE", Namesake = "ORACHE", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 20, Name= "SARCLOIR", Namesake = "WEEDING HOE", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 21, Name= "STATICE", Namesake = "SEA THRIFT", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 22, Name= "FRITILLAIRE", Namesake = "FRITILLARY", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 23, Name= "BOURRACHE", Namesake = "BORAGE", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 24, Name= "VALERIANE", Namesake = "VALERIAN", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 25, Name= "CARPE", Namesake = "CARP", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 26, Name= "FUSAIN", Namesake = "EUONYMUS", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 27, Name= "CIVETTE", Namesake = "CHIVES", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 28, Name= "BUGLOSSE", Namesake = "BUGLOSS", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 29, Name= "SENEVE", Namesake = "WHITE MUSTARD", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 30, Name= "HOULETTE", Namesake = "SHEPHERD'S CROOK", Month = RepublicanMonth.Floreal },
            new RepublicanDayName { Day = 1, Name= "LUZERNE", Namesake = "LUCERNE", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 2, Name= "HEMEROCALLE", Namesake = "DAYLILY", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 3, Name= "TREFLE", Namesake = "CLOVER", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 4, Name= "ANGELIQUE", Namesake = "ANGELICA", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 5, Name= "CANARD", Namesake = "DUCK", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 6, Name= "MELISSE", Namesake = "LEMON BALM", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 7, Name= "FROMENTAL", Namesake = "OAT GRASS", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 8, Name= "MARTAGON", Namesake = "MARTAGON LILY", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 9, Name= "SERPOLET", Namesake = "WILD THYME", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 10, Name= "FAUX", Namesake = "SCYTHE", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 11, Name= "FRAISE", Namesake = "STRAWBERRY", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 12, Name= "BETOINE", Namesake = "BETONY", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 13, Name= "POIS", Namesake = "PEA", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 14, Name= "ACACIA", Namesake = "ACACIA", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 15, Name= "CAILLE", Namesake = "QUAIL", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 16, Name= "OEILLET", Namesake = "CARNATION", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 17, Name= "SUREAU", Namesake = "ELDERBERRY", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 18, Name= "PAVOT", Namesake = "POPPY PLANT", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 19, Name= "TILLEUL", Namesake = "LINDEN OR LIME TREE", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 20, Name= "FOURCHE", Namesake = "PITCHFORK", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 21, Name= "BARBEAU", Namesake = "CORNFLOWER", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 22, Name= "CAMOMILLE", Namesake = "CAMOMILE", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 23, Name= "CHEVREFEUILLE", Namesake = "HONEYSUCKLE", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 24, Name= "CAILLE-LAIT", Namesake = "BEDSTRAW", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 25, Name= "TANCHE", Namesake = "TENCH", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 26, Name= "JASMIN", Namesake = "JASMINE", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 27, Name= "VERVEINE", Namesake = "VERVAIN", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 28, Name= "THYM", Namesake = "THYME", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 29, Name= "PIVOINE", Namesake = "PEONY", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 30, Name= "CHARIOT", Namesake = "HANDCART", Month = RepublicanMonth.Prairial },
            new RepublicanDayName { Day = 1, Name= "SEIGLE", Namesake = "RYE", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 2, Name= "AVOINE", Namesake = "OAT", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 3, Name= "OIGNON", Namesake = "ONION", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 4, Name= "VERONIQUE", Namesake = "SPEEDWELL", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 5, Name= "MULET", Namesake = "MULE", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 6, Name= "ROMARIN", Namesake = "ROSEMARY", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 7, Name= "CONCOMBRE", Namesake = "CUCUMBER", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 8, Name= "ECHALOTE", Namesake = "SHALLOT", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 9, Name= "ABSINTHE", Namesake = "WORMWOOD", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 10, Name= "FAUCILLE", Namesake = "SICKLE", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 11, Name= "CORIANDRE", Namesake = "CORIANDER", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 12, Name= "ARTICHAUT", Namesake = "ARTICHOKE", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 13, Name= "GIROFLE", Namesake = "CLOVE", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 14, Name= "LAVANDE", Namesake = "LAVENDER", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 15, Name= "CHAMOIS", Namesake = "CHAMOIS", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 16, Name= "TABAC", Namesake = "TOBACCO", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 17, Name= "GROSEILLE", Namesake = "REDCURRANT", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 18, Name= "GESSE", Namesake = "HAIRY VETCHLING", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 19, Name= "CERISE", Namesake = "CHERRY", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 20, Name= "PARC", Namesake = "LIVESTOCK PEN", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 21, Name= "MENTHE", Namesake = "MINT", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 22, Name= "CUMIN", Namesake = "CUMIN", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 23, Name= "HARICOT", Namesake = "BEAN", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 24, Name= "ORCANETE", Namesake = "ALKANET", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 25, Name= "PINTADE", Namesake = "GUINEAFOWL", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 26, Name= "SAUGE", Namesake = "SAGE", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 27, Name= "AIL", Namesake = "GARLIC", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 28, Name= "VESCE", Namesake = "TARE", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 29, Name= "BLE", Namesake = "WHEAT", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 30, Name= "CHALEMIE", Namesake = "SHAWM", Month = RepublicanMonth.Messidor },
            new RepublicanDayName { Day = 1, Name= "EPEAUTRE", Namesake = "SPELT", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 2, Name= "BOUILLON BLANC", Namesake = "COMMON MULLEIN", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 3, Name= "MELON", Namesake = "MELON", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 4, Name= "IVRAIE", Namesake = "RYEGRASS", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 5, Name= "BELIER", Namesake = "RAM", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 6, Name= "PRELE", Namesake = "HORSETAIL", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 7, Name= "ARMOISE", Namesake = "MUGWORT", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 8, Name= "CARTHAME", Namesake = "SAFFLOWER", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 9, Name= "MURE", Namesake = "BLACKBERRY", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 10, Name= "ARROSOIR", Namesake = "WATERING CAN", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 11, Name= "PANIC", Namesake = "FOXTAIL MILLET", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 12, Name= "SALICORNE", Namesake = "COMMON GLASSWORT", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 13, Name= "ABRICOT", Namesake = "APRICOT", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 14, Name= "BASILIC", Namesake = "BASIL", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 15, Name= "BREBIS", Namesake = "EWE", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 16, Name= "GUIMAUVE", Namesake = "MARSHMALLOW", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 17, Name= "LIN", Namesake = "FLAX", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 18, Name= "AMANDE", Namesake = "ALMOND", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 19, Name= "GENTIANE", Namesake = "GENTIAN", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 20, Name= "ECLUSE", Namesake = "LOCK", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 21, Name= "CARLINE", Namesake = "CARLINE THISTLE", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 22, Name= "CAPRIER", Namesake = "CAPER", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 23, Name= "LENTILLE", Namesake = "LENTIL", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 24, Name= "AUNEE", Namesake = "INULA", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 25, Name= "LOUTRE", Namesake = "OTTER", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 26, Name= "MYRTE", Namesake = "MYRTLE", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 27, Name= "COLZA", Namesake = "RAPESEED", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 28, Name= "LUPIN", Namesake = "LUPIN", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 29, Name= "COTON", Namesake = "COTTON", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 30, Name= "MOULIN", Namesake = "MILL", Month = RepublicanMonth.Thermidor },
            new RepublicanDayName { Day = 1, Name= "PRUNE", Namesake = "PLUM", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 2, Name= "MILLET", Namesake = "MILLET", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 3, Name= "LYCOPERDON", Namesake = "PUFFBALL", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 4, Name= "ESCOURGEON", Namesake = "SIX-ROW BARLEY", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 5, Name= "SAUMON", Namesake = "SALMON", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 6, Name= "TUBEREUSE", Namesake = "TUBEROSE", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 7, Name= "SUCRION", Namesake = "WINTER BARLEY", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 8, Name= "APOCYN", Namesake = "APOCYNUM", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 9, Name= "REGLISSE", Namesake = "LIQUORICE", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 10, Name= "ECHELLE", Namesake = "LADDER", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 11, Name= "PASTEQUE", Namesake = "WATERMELON", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 12, Name= "FENOUIL", Namesake = "FENNEL", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 13, Name= "EPINE VINETTE", Namesake = "EUROPEAN BARBERRY", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 14, Name= "NOIX", Namesake = "WALNUT", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 15, Name= "TRUITE", Namesake = "TROUT", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 16, Name= "CITRON", Namesake = "LEMON", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 17, Name= "CARDERE", Namesake = "TEASEL", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 18, Name= "NERPRUN", Namesake = "BUCKTHORN", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 19, Name= "TAGETTE", Namesake = "MEXICAN MARIGOLD", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 20, Name= "HOTTE", Namesake = "HARVESTING BASKET", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 21, Name= "EGLANTIER", Namesake = "WILD ROSE", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 22, Name= "NOISETTE", Namesake = "HAZELNUT", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 23, Name= "HOUBLON", Namesake = "HOPS", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 24, Name= "SORGHO", Namesake = "SORGHUM", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 25, Name= "ECREVISSE", Namesake = "CRAYFISH", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 26, Name= "BIGARADE", Namesake = "BITTER ORANGE", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 27, Name= "VERGE D'OR", Namesake = "GOLDENROD", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 28, Name= "MAIS", Namesake = "MAIZE", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 29, Name= "MARRON", Namesake = "SWEET CHESTNUT", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 30, Name= "PANIER", Namesake = "PACK BASKET", Month = RepublicanMonth.Fructidor },
            new RepublicanDayName { Day = 1, Name = "VERTU", Namesake = "VIRTUE", Month = RepublicanMonth.SansCulottides},
            new RepublicanDayName { Day = 2, Name = "GENIE", Namesake = "TALENT", Month = RepublicanMonth.SansCulottides},
            new RepublicanDayName { Day = 3, Name = "TRAVAIL", Namesake = "LABOUR", Month = RepublicanMonth.SansCulottides},
            new RepublicanDayName { Day = 4, Name = "OPINION", Namesake = "CONVICTIONS", Month = RepublicanMonth.SansCulottides},
            new RepublicanDayName { Day = 5, Name = "RECOMPENSES", Namesake = "HONOURS", Month = RepublicanMonth.SansCulottides},
            new RepublicanDayName { Day = 6, Name = "REVOLUTION", Namesake = "REVOLUTION", Month = RepublicanMonth.SansCulottides}
        };

        public static RepublicanDayName Get(int day, RepublicanMonth month) => RepublicanDays.Single(d => d.Day == day && d.Month == month);
    }
}
